import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '../../../libs/database'
import { DriverSchema } from '../../../types'
import { z } from 'zod'
import { DriverStatus, Prisma } from '@prisma/client'
import { UberSyncService } from '../../../libs/uber-sync'
import { parse } from 'json2csv'
import formidable from 'formidable'
import fs from 'fs/promises'
import Papa from 'papaparse'
import type { Fields, Files, File } from 'formidable'
import { getGradeFromScore } from '../../../libs/driver-scoring'

// Instantiate the UberSyncService
const uberSyncService = new UberSyncService()

// GET /api/drivers - List all drivers
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const email = searchParams.get('email')
    const uberDriverId = searchParams.get('uberDriverId')
    const limit = parseInt(searchParams.get('limit') || '100')
    const offset = parseInt(searchParams.get('offset') || '0')
    const driverId = searchParams.get('driverId')
    const type = searchParams.get('type')
    const status = searchParams.get('status')
    const reason = searchParams.get('reason')
    const from = searchParams.get('from')
    const to = searchParams.get('to')

    // If email or uberDriverId is present, filter by those fields only
    if (email || uberDriverId) {
      const where: any = {}
      if (email) where.email = email
      if (uberDriverId) where.uberDriverId = uberDriverId
      const drivers = await prisma.driver.findMany({ where })
      return NextResponse.json({ success: true, data: drivers })
    }

    // If no alert filters are present, return all drivers with performance and alert data
    if (!driverId && !type && !status && !reason && !from && !to) {
      const drivers = await prisma.driver.findMany({})
      // For each driver, fetch latest metric and alert count
      const driverData = await Promise.all(drivers.map(async (driver) => {
        // Latest metric
        const lastMetric = await prisma.driverMetrics.findFirst({
          where: { driverId: driver.id },
          orderBy: { date: 'desc' }
        })
        // Alert count
        const recentAlertsCount = await prisma.alertRecord.count({
          where: { driverId: driver.id }
        })
        // Calculate grade from calculatedScore
        let grade = null
        if (lastMetric && typeof lastMetric.calculatedScore === 'number') {
          grade = getGradeFromScore(lastMetric.calculatedScore)
        }
        return {
          ...driver,
          lastMetrics: lastMetric ? {
            calculatedScore: lastMetric.calculatedScore,
            acceptanceRate: lastMetric.acceptanceRate,
            cancellationRate: lastMetric.cancellationRate,
            completionRate: lastMetric.completionRate,
            feedbackScore: lastMetric.feedbackScore,
            tripVolume: lastMetric.tripVolumeIndex,
            idleRatio: lastMetric.idleRatio,
            grade
          } : null,
          currentScore: lastMetric ? lastMetric.calculatedScore : null,
          recentAlertsCount
        }
      }))
      return NextResponse.json({ success: true, data: driverData })
    }

    const where: any = {}
    if (driverId) where.driverId = driverId
    if (type) where.alertType = type.toUpperCase()
    if (status) where.status = status.toUpperCase()
    if (reason) where.reason = reason
    if (from || to) {
      where.createdAt = {}
      if (from) where.createdAt.gte = new Date(from)
      if (to) where.createdAt.lte = new Date(to)
    }

    const alerts = await prisma.alertRecord.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      skip: offset,
      take: limit,
      include: { driver: true }
    })
    const total = await prisma.alertRecord.count({ where })
    return NextResponse.json({
      success: true,
      data: alerts.map(alert => ({
        ...alert,
        conversationId: alert.conversationId
      })),
      total
    })
  } catch (error) {
    console.error('Failed to fetch alerts:', error)
    return NextResponse.json({ success: false, error: 'Failed to fetch alerts' }, { status: 500 })
  }
}

// POST /api/drivers - Create a new driver
/**
 * POST /api/drivers
 * Creates a new driver record in the database
 * 
 * @param request - The incoming HTTP request containing driver data
 * @returns JSON response with created driver data or error message
 */
export async function POST(request: NextRequest) {
  console.log('POST /api/drivers - Creating new driver')
  try {
    // Parse the request body into JSON
    const body = await request.json()
    console.log('Received request body:', body)
    
    // Create a validation schema by omitting auto-generated fields
    // from the base DriverSchema
    const CreateDriverSchema = DriverSchema.omit({ 
      id: true, // UUID will be generated by database
      joinedAt: true, // Will be set to current timestamp
      updatedAt: true // Will be set to current timestamp
    })
    console.log('Created validation schema')
    
    // Validate the request data against our schema
    const validatedData = CreateDriverSchema.parse(body)
    console.log('Data validation successful:', validatedData)

    // Check for existing drivers with same email or Uber ID
    // to prevent duplicate entries
    console.log('Checking for existing drivers with email:', validatedData.email, 'or Uber ID:', validatedData.uberDriverId)
    const existingDriver = await prisma.driver.findFirst({
      where: {
        OR: [
          { email: validatedData.email },
          { uberDriverId: validatedData.uberDriverId }
        ]
      }
    })

    // Return error if driver already exists
    if (existingDriver) {
      console.log('Driver already exists:', existingDriver)
      return NextResponse.json({
        success: false,
        error: 'Driver with this email or Uber ID already exists',
        timestamp: new Date()
      }, { status: 400 })
    }

    // Create new driver record in database
    // Type assertion needed due to Prisma's type system
    console.log('Creating new driver record with data:', validatedData)
    const driver = await prisma.driver.create({
      data: validatedData as unknown as Prisma.DriverCreateInput
    })
    console.log('Driver created successfully:', driver)

    // Return success response with created driver data
    return NextResponse.json({
      success: true,
      data: driver,
      timestamp: new Date()
    }, { status: 201 })

  } catch (error) {
    // Log the error for debugging
    console.error('Error creating driver:', error)
    
    // Handle validation errors specifically
    if (error instanceof z.ZodError) {
      console.log('Validation error details:', error.errors)
      return NextResponse.json({
        success: false,
        error: 'Validation error',
        details: error.errors,
        timestamp: new Date()
      }, { status: 400 })
    }

    // Handle all other errors
    console.error('Unexpected error occurred:', error)
    return NextResponse.json({
      success: false,
      error: 'Failed to create driver',
      timestamp: new Date()
    }, { status: 500 })
  }
}

// GET /api/drivers/export - Export all drivers as CSV
export async function GET_EXPORT(request: NextRequest) {
  try {
    const drivers = await prisma.driver.findMany({})
    const fields = ['name', 'email', 'phone', 'uberDriverId', 'status', 'language']
    const opts = { fields }
    const csv = parse(drivers, opts)
    return new Response(csv, {
      status: 200,
      headers: {
        'Content-Type': 'text/csv',
        'Content-Disposition': 'attachment; filename="drivers-export.csv"',
      },
    })
  } catch (error) {
    return NextResponse.json({ success: false, error: 'Failed to export drivers' }, { status: 500 })
  }
}

// POST /api/drivers/import - Bulk import drivers from CSV
export const config = { api: { bodyParser: false } }
export async function POST_IMPORT(request: NextRequest) {
  try {
    // Parse multipart form
    const form = formidable({ multiples: false })
    const [fields, files] = await new Promise<[Fields, Files]>((resolve, reject) => {
      form.parse(request as any, (err: any, fields: Fields, files: Files) => {
        if (err) reject(err)
        else resolve([fields, files])
      })
    })
    let fileObj:any = files.file || files.csv
    if (!fileObj) return NextResponse.json({ success: false, error: 'No file uploaded' }, { status: 400 })
    if (Array.isArray(fileObj)) fileObj = fileObj[0]
    if (!fileObj || Array.isArray(fileObj)) return NextResponse.json({ success: false, error: 'Invalid file upload' }, { status: 400 })
    const file = fileObj as unknown as File
    const csvContent = await fs.readFile(file.filepath, 'utf8')
    const { data, errors } = Papa.parse(csvContent, { header: true, skipEmptyLines: true })
    if (errors.length > 0) {
      return NextResponse.json({ success: false, error: 'CSV parse error', details: errors }, { status: 400 })
    }
    // Validate and insert
    const results = []
    let successCount = 0
    let errorCount = 0
    for (const row of data) {
      const { name, email, phone, uberDriverId, status, language } = row as any
      if (!name || !email || !phone || !status || !language) {
        results.push({ row, error: 'Missing required fields' }); errorCount++; continue
      }
      // Check for existing
      const existing = await prisma.driver.findFirst({ where: { OR: [{ email }, { uberDriverId }] } })
      if (existing) {
        results.push({ row, error: 'Duplicate email or Uber ID' }); errorCount++; continue
      }
      try {
        await prisma.driver.create({ data: { name, email, phone, uberDriverId, status, language } })
        results.push({ row, success: true }); successCount++
      } catch (err) {
        results.push({ row, error: 'DB error' }); errorCount++
      }
    }
    return NextResponse.json({ success: true, successCount, errorCount, results })
  } catch (error) {
    return NextResponse.json({ success: false, error: 'Failed to import drivers' }, { status: 500 })
  }
} 